"""initial

Revision ID: 51b7f92bd06c
Revises: None
Create Date: 2014-10-10 09:53:35.624472

"""

# revision identifiers, used by Alembic.
revision = '51b7f92bd06c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    op.drop_column('mailinglist', 'acceptable_aliases_id')
    op.create_index(op.f('ix_user__user_id'), 'user', ['_user_id'], unique=False)
    op.drop_index('ix_user_user_id', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version')
    op.create_index('ix_user_user_id', 'user', ['_user_id'], unique=False)
    op.drop_index(op.f('ix_user__user_id'), table_name='user')
    op.add_column('mailinglist', sa.Column('acceptable_aliases_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
